"use client";

import React from 'react';
import { ServicesHero } from '../../components/ServicesHero';
import { ServicesSection } from "../../components/ServicesSection.jsx";
import { WhyChooseUs } from "../../components/WhyChooseUs.jsx";
import { Works } from "../../components/Works.jsx";
import Map from '../../components/Map.jsx';
import { AdvancedFeatures } from '../../components/AdvancedFeatures';
import { ForDrivers } from '../../components/ForDrivers';
import Taxi from '../../components/Taxi.jsx';

import { useLanguage } from "../../Context/LanguageContext";
import { servicesHeroTranslations } from "../../translations/servicesHeroTranslations";

// export const metadata = {
//     title: "Ride With Us",
//     description: "Generated by create next app",
// };

const Ride = () => {
    const { language } = useLanguage();
    const t =
        servicesHeroTranslations[language] ||
        servicesHeroTranslations.English;

    return (
        <>
            <ServicesHero
                subtitle={t.subtitle}
                title={t.title}
                description={t.description}
            />

            <Map />
            <AdvancedFeatures />
            <ForDrivers />
            <ServicesSection />
            <Taxi />
        </>
    );
};

export default Ride;
